# ===== Spring Boot Application =====
spring.application.name=quantity-measurement-app


spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=8770B26@k

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=I6wXAmQ2zritQpirEjxQWiX3sQWrN76xLYFE0uUbAZg
jwt.expiration=86400000


logging.level.org.springframework.web=DEBUG


# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23livyFdoXFtZBALuG
spring.security.oauth2.client.registration.github.client-secret=c96bb774df6cf1985099ffb3f95272db3d4dc9e8

spring.security.oauth2.client.registration.github.scope=user:email